export const fieldLabels = {
  motorista: 'Motorista',
  loggedInUser: 'Usuário logado',
  createdAt: 'Timestamp',
  dataString: 'Data',
  liberada: 'Liberada',
  motoristaUid: 'UID do motorista',
  'veiculo_comum.combustivel': 'Combustível acima de ½ tanque',
  'veiculo_comum.oleo': 'Óleo do motor',
  'veiculo_comum.agua': 'Água do radiador',
  'veiculo_comum.pneus': 'Pneus calibrados',
  'veiculo_comum.estepe': 'Estepe em condições',
  'veiculo_comum.macaco': 'Macaco e chave de roda',
  'veiculo_comum.luzes': 'Luz alta e baixa',
  'veiculo_comum.limpador': 'Limpador de para-brisa',
  'veiculo_comum.arCondicionado': 'Ar-condicionado',
  'veiculo_ambulancia.setas': 'Setas e luz de freio',
  'veiculo_ambulancia.giroflex': 'Giroflex funcionando',
  'veiculo_ambulancia.sirene': 'Sirene funcionando',
  'veiculo_ambulancia.maca': 'Maca principal funcionando',
  'veiculo_ambulancia.travasMaca': 'Travas da maca',
  'imobilizacao.prancha': 'Prancha longa',
  'imobilizacao.cintoAranha': 'Cinto aranha',
  'imobilizacao.headBlock': 'Tirante de cabeça (head block)',
  'imobilizacao.colares': 'Colares cervicais',
  'imobilizacao.talas': 'Talas de imobilização',
  'imobilizacao.bandagens': 'Bandagens triangulares',
  'imobilizacao.cobertor': 'Cobertor/manta térmica',
  'imobilizacao.cadeiraRemocao': 'Cadeira de rodas/remoção',
  'oxigenacao.cilindroCheio': 'Cilindro de oxigênio cheio',
  'oxigenacao.cilindroReserva': 'Cilindro reserva',
  'oxigenacao.fluxometro': 'Fluxômetro e umidificador',
  'oxigenacao.umidificador': 'Umidificador',
  'oxigenacao.mascaraAdulto': 'Máscara O2 adulto',
  'oxigenacao.mascaraPed': 'Máscara O2 ped',
  'oxigenacao.mascaraReservatorio': 'Máscara de reservatório',
  'oxigenacao.ambuAdulto': 'Ambu adulto',
  'oxigenacao.ambuPed': 'Ambu ped',
  'oxigenacao.aspirador': 'Aspirador portátil',
  'biosseguranca.lixoInfectante': 'Lixo infectante',
  'biosseguranca.lixoComum': 'Lixo comum',
  'biosseguranca.desinfetante': 'Desinfetante e papel-toalha',
  'biosseguranca.papelToalha': 'Papel toalha',
  'biosseguranca.caixaPerfuro': 'Caixa coletora perfurocortante',
  driverName: 'Nome do motorista',
  veiculoNome: 'Nome do veículo',
  kilometragem: 'Kilometragem',
  local: 'Local',
  vehicleType: 'Tipo de veículo',
  'documentacao.crlv': 'CRLV / documento do veículo em dia',
  'documentacao.licenciamento': 'Licenciamento pago',
  'documentacao.seguro': 'Seguro obrigatório / seguro do veículo',
  'documentacao.manual': 'Manual do proprietário no carro',
  'parte_externa.pintura': 'Estado geral da pintura',
  'parte_externa.riscos': 'Presença de riscos, amassados ou ferrugem',
  'parte_externa.alinhamento': 'Alinhamento de portas, capô e porta-malas',
  'parte_externa.vidros': 'Vidros sem trincas ou rachaduras',
  'parte_externa.retrovisores': 'Retrovisores firmes e íntegros',
  'pneus_rodas.desgaste': 'Desgaste uniforme dos pneus',
  'pneus_rodas.sulcos': 'Sulcos acima do limite mínimo',
  'iluminacao_carro.lanternas': 'Lanternas traseiras',
  'iluminacao_carro.luz_freio': 'Luz de freio',
  'iluminacao_carro.luz_re': 'Luz de ré',
  'iluminacao_carro.setas': 'Setas',
  'iluminacao_carro.luz_placa': 'Luz de placa',
  'iluminacao_carro.farol_neblina': 'Farol de neblina (se houver)',
  'interior.cintos': 'Funcionamento dos cintos de segurança',
  'interior.bancos': 'Bancos firmes e regulagem funcionando',
  'interior.painel': 'Painel sem alertas acesos',
  'interior.vidros_eletricos': 'Vidros elétricos',
  'interior.travamento': 'Travamento das portas',
  'interior.buzina': 'Buzina funcionando',
  'motor_fluidos.arrefecimento': 'Nível do líquido de arrefecimento',
  'motor_fluidos.freio': 'Fluído de freio',
  'motor_fluidos.vazamentos': 'Vazamentos aparentes no motor',
  'freios.pedal': 'Pedal de freio firme',
  'freios.freio_mao': 'Freio de mão funcionando',
  'freios.ruidos': 'Ausência de ruídos ao frear',
  'suspensao_direcao.ruidos': 'Sem ruídos ao passar em irregularidades',
  'suspensao_direcao.direcao': 'Direção alinhada',
  'suspensao_direcao.volante': 'Volante sem vibrações',
  'equipamentos.triangulo': 'Triângulo de sinalização',
};
